=== Djorgiii/Semestre3/Semestre4/IECD/TP1/JogoGalo/jogGalo/metodos-cli.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="metodo" type="metodoType">
		<xs:annotation>
			<xs:documentation>
				Elemento raíz que representa respostas envidadas
				pelo servidor
				que correspondem ao retorno de métodos de interação com o jogo.
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="metodoType">
		<xs:annotation>
			<xs:documentation>Tipo complexo que define os métodos disponíveis
				para interação durante o jogo.
			</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:element type="iniciarType" name="iniciar">
				<xs:annotation>
					<xs:documentation>Metodo para iniciar um jogo.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="obterType" name="obter">
				<xs:annotation>
					<xs:documentation>Metodo para obter o tabuleiro atual.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element type="jogarType" name="jogar">
				<xs:annotation>
					<xs:documentation>Metodo para assinalar uma jogada no tabuleiro.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="iniciarType">
		<xs:sequence>
			<xs:element type="jogadorType" name="jogador"
				minOccurs="1">
				<xs:annotation>
					<xs:documentation>Símbolo associado ao jogador atual.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="xs:token" name="nickname"
			use="required">
			<xs:annotation>
				<xs:documentation>Nome curto do jogador para iniciar o jogo.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute type="xs:token" name="senha" use="required">
			<xs:annotation>
				<xs:documentation>Senha do jogador para iniciar o jogo.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="obterType">
		<xs:sequence>
			<xs:element type="tabuleiroType" name="tabuleiro"
				minOccurs="1">
				<xs:annotation>
					<xs:documentation>Obtém o tabuleiro atual.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="jogarType">
		<xs:attribute type="jogadaType" name="jogada" use="required">
			<xs:annotation>
				<xs:documentation>Assinala jogada realizada (entre 1 e 9).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="jogadaType">
		<xs:annotation>
			<xs:documentation>Tipo para representar uma jogada válida, que é um
				valor numérico entre 1 e 9.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:byte">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="9" />
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="simboloType">
		<xs:annotation>
			<xs:documentation>Tipo que representa o símbolo do jogador (X ou O).
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="X" />
			<xs:enumeration value="O" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="jogadorType">
		<xs:annotation>
			<xs:documentation>Tipo (não especificado) que representa o jogador
				mas inclui o símbolo.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:any processContents="skip" namespace="##any" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute type="simboloType" name="simbolo"
			use="required">
			<xs:annotation>
				<xs:documentation>Símbolo do jogador X/O</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="jogadaCombinadaType">
		<xs:annotation>
			<xs:documentation>Tipo que permite representar tanto uma jogada
				numérica quanto um simbolo de jogador.
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="jogadaType simboloType" />
	</xs:simpleType>
	<xs:simpleType name="estadoType">
		<xs:annotation>
			<xs:documentation>Tipo para representar o estado do jogo (Vitória O,
				Vitória X, Empate, Jogada Inválida, Nada a registar).
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="VX" />
			<xs:enumeration value="VO" />
			<xs:enumeration value="EM" />
			<xs:enumeration value="IV" />
			<xs:enumeration value="ND" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="casaType">
		<xs:attribute type="jogadaCombinadaType" name="simbolo"
			use="required">
			<xs:annotation>
				<xs:documentation>Símbolo do jogador que ocupou a casa (número
					da
					casa ou símbolo X/O).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="tabuleiroType">
		<xs:sequence>
			<xs:element type="casaType" name="casa" maxOccurs="9"
				minOccurs="9">
				<xs:annotation>
					<xs:documentation>Elemento que representa uma casa no tabuleiro.
					</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute type="estadoType" name="estado"
			use="required">
			<xs:annotation>
				<xs:documentation>Estado do jogo (Vitória O,
					Vitória X, Empate,
					Jogada Inválida, Nada a registar).
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== Djorgiii/Semestre3/Semestre4/IECD/TP1/PontoCaixas/PontoCaixas/teste.xsd/ex5.xml
<?xml version="1.0" encoding="UTF-8"?>
<metodo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="metodos-cli.xsd">
	<obter>
		<tabuleiro estado="ND">
			<casa simbolo="X" />
			<casa simbolo="2" />
			<casa simbolo="3" />
			<casa simbolo="4" />
			<casa simbolo="5" />
			<casa simbolo="6" />
			<casa simbolo="7" />
			<casa simbolo="8" />
			<casa simbolo="9" />
		</tabuleiro>
	</obter>
</metodo>

=== Djorgiii/Semestre3/Semestre4/IECD/TP1/JogoGalo (1)/jogGalo/teste.xsd/ex6.xml
<?xml version="1.0" encoding="UTF-8"?>
<metodo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="metodos-cli.xsd">
	<obter>
		<tabuleiro estado="EM">
			<casa simbolo="X" />
			<casa simbolo="O" />
			<casa simbolo="X" />
			<casa simbolo="O" />
			<casa simbolo="X" />
			<casa simbolo="O" />
			<casa simbolo="X" />
			<casa simbolo="O" />
			<casa simbolo="X" />
		</tabuleiro>
	</obter>
</metodo>

=== Djorgiii/Semestre3/Semestre4/IECD/TP1/JogoGalo (1)/jogGalo/teste.xsd/ex7.xml
<?xml version="1.0" encoding="UTF-8"?>
<metodo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="metodos-cli.xsd">
	<obter>
		<tabuleiro estado="VX">
			<casa simbolo="X" />
			<casa simbolo="O" />
			<casa simbolo="X" />
			<casa simbolo="O" />
			<casa simbolo="X" />
			<casa simbolo="O" />
			<casa simbolo="X" />
			<casa simbolo="8" />
			<casa simbolo="9" />
		</tabuleiro>
	</obter>
</metodo>
